1.19.2 forge
KiroTheBlueFox/MoBlocks pull request #11
Opened 2023-07-08 11:27 UTC by Mysticpasta1

this is meant for a 1.19.2 forge branch if you need me to re PR I will :D

2023-07-08 11:28 UTC, Mysticpasta1 commented
btw the 1.19.2 commit is because intellij broke and deleted 3 - 4 hours of work on one of the class

2023-07-10 18:59 UTC, hypherionmc requested changes
Just some changes. Also please edit your commit message. This mod doesn't belong to either of us and I don't think Kiro would like swearing in the commits

2023-07-10 18:59 UTC, hypherionmc commented on build.gradle
> +version = '1.0.0'
Please don't bump to 1.0.0. Bump to 0.11.0 instead

2023-07-10 18:59 UTC, hypherionmc commented on src/main/java/kirothebluefox/moblocks/content/ModBlocks.java
Are you sure this file is no longer needed?

Pretty sure these references were set dynamically by forge using `@ObjectHolder`. Same for the other classes you deleted

2023-07-10 21:52 UTC, Mysticpasta1 commented on src/main/java/kirothebluefox/moblocks/content/ModBlocks.java
The `@ObjectHolder` annotation is removed on 1.19.2 forge and should be replaced in your registry class with `DefferedRegistry` or whatever it is called now. Also due to intellij wiping out 3 - 4 hours of work I just left the giant registry class alone, which will need to be fully rewritten!

2023-07-10 21:53 UTC, Mysticpasta1 commented
I fixed the swearing on that commit I was just angry at intellij deleting 3 - 4 hours of work

2023-07-11 07:49 UTC, hypherionmc commented on src/main/java/kirothebluefox/moblocks/content/ModBlocks.java
Fair enough. Yeah as I mentioned to you in discord, major parts of the mod need to be rewritten, especially if we plan on going above 1.19.2, but I'll speak with you then we can tackle that later on.

For now, the PR looks good

2023-07-11 07:51 UTC, merged